[package]
name = "CitySim"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
bitflags = "2.9.0"
paste = "1.0.15"
gl = "0.14.0"
glfw = "0.59.0"
imgui = "0.11"
imgui-opengl-renderer = "0.12.1"
libc = "0.2"
arrayvec = "0.7.6"
smallvec = "1.15.0"
strum = "0.27"
strum_macros = "0.27"
