use super::{Size, Vec2};

// i32/Size
pub const BASE_TILE_WIDTH_I32:  i32 = 64;
pub const BASE_TILE_HEIGHT_I32: i32 = 32;
pub const BASE_TILE_SIZE_I32:  Size = Size { width: BASE_TILE_WIDTH_I32, height: BASE_TILE_HEIGHT_I32 };

pub const HALF_BASE_TILE_WIDTH_I32:  i32 = BASE_TILE_WIDTH_I32  / 2;
pub const HALF_BASE_TILE_HEIGHT_I32: i32 = BASE_TILE_HEIGHT_I32 / 2;
pub const HALF_BASE_TILE_SIZE_I32:  Size = Size { width: HALF_BASE_TILE_WIDTH_I32, height: HALF_BASE_TILE_HEIGHT_I32 };

// f32/Vec2
pub const BASE_TILE_WIDTH_F32:  f32 = 64.0;
pub const BASE_TILE_HEIGHT_F32: f32 = 32.0;
pub const BASE_TILE_SIZE_F32:  Vec2 = Vec2 { x: BASE_TILE_WIDTH_F32, y: BASE_TILE_HEIGHT_F32 };

pub const HALF_BASE_TILE_WIDTH_F32:  f32 = BASE_TILE_WIDTH_F32  / 2.0;
pub const HALF_BASE_TILE_HEIGHT_F32: f32 = BASE_TILE_HEIGHT_F32 / 2.0;
pub const HALF_BASE_TILE_SIZE_F32:  Vec2 = Vec2 { x: HALF_BASE_TILE_WIDTH_F32, y: HALF_BASE_TILE_HEIGHT_F32 };
